Merge feature/viewmodelfactory-non-generic-methods into develop
UltimateCodeMonkeys/CodeMonkeys pull request #137
Opened 2020-06-27 14:05 UTC by LegendaryB

Closes #136

2020-06-27 14:06 UTC, Pantheas commented on src/MVVM/Factories/ViewModelFactory.cs
> +                        $"The type {viewModelType.Name} must implement interface type {interfaceType.Name}");
Codacy found an issue: [Refactor this method to add validation of parameter 'viewModelType' before using it.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060)

2020-06-27 14:06 UTC, Pantheas commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 6
           

Complexity increasing per file
==============================
- src/MVVM/Factories/ViewModelFactory.cs  1
         

Clones added
============
- src/MVVM/Factories/ViewModelFactory.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060&bid=18874753)

2020-06-27 14:06 UTC, Pantheas commented on src/MVVM/Factories/ViewModelFactory.cs
> +        /// <param name="initialize">Specifies if <see cref="IViewModel.InitializeAsync"/> should get called after instance creation.</param>
Codacy found an issue: [Split this 141 characters long line (which is greater than 130 authorized).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060)

2020-06-27 14:06 UTC, Pantheas commented on src/MVVM/Factories/ViewModelFactory.cs
> +        /// <param name="model">Parameter that will be passed in the <see cref="IViewModel{TModel}.InitializeAsync(TModel)"/> method</param>
Codacy found an issue: [Split this 140 characters long line (which is greater than 130 authorized).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060)

2020-06-27 14:06 UTC, Pantheas commented on src/MVVM/Factories/ViewModelFactory.cs
> +        /// <typeparam name="TModel">Type of the parameter that will be passed in the <see cref="IViewModel{TModel}.InitializeAsync(TModel)"/> method</typeparam>
Codacy found an issue: [Split this 161 characters long line (which is greater than 130 authorized).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060)

2020-06-27 14:06 UTC, Pantheas commented on src/MVVM/Factories/ViewModelFactory.cs
> +        public static async Task<TViewModel> ResolveAsync<TViewModel>(
Codacy found an issue: [All 'ResolveAsync' method overloads should be adjacent.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060)

2020-06-27 14:06 UTC, Pantheas commented on src/MVVM/Factories/ViewModelFactory.cs
> +        public static TViewModel Resolve<TViewModel>(
Codacy found an issue: [All 'Resolve' method overloads should be adjacent.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060)

2020-06-28 00:52 UTC, LegendaryB commented
Leave open, identified a bug. Will fix asap

2020-06-29 07:18 UTC, Pantheas requested changes
Fix Codacy issues, I will approve afterwards :)

2020-06-29 08:29 UTC, Pantheas commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 4
           

Complexity increasing per file
==============================
- src/MVVM/Factories/ViewModelFactory.cs  1
         

Clones added
============
- src/MVVM/Factories/ViewModelFactory.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060&bid=18874753)

2020-06-29 08:29 UTC, Pantheas commented on src/MVVM/Factories/ViewModelFactory.cs
> +        /// <param name="model">Parameter that will be passed in the <see cref="IViewModel{TModel}.InitializeAsync(TModel)"/> method</param>
Codacy found an issue: [Split this 140 characters long line (which is greater than 130 authorized).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060)

2020-06-29 08:30 UTC, Pantheas commented on src/MVVM/Factories/ViewModelFactory.cs
> +                        $"The type {viewModelType.Name} must implement interface type {interfaceType.Name}");
Codacy found an issue: [Refactor this method to add validation of parameter 'viewModelType' before using it.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060)

2020-06-29 08:30 UTC, Pantheas commented on src/MVVM/Factories/ViewModelFactory.cs
> +        /// <typeparam name="TModel">Type of the parameter that will be passed in the <see cref="IViewModel{TModel}.InitializeAsync(TModel)"/> method</typeparam>
Codacy found an issue: [Split this 161 characters long line (which is greater than 130 authorized).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060)

2020-06-29 08:30 UTC, Pantheas commented on src/MVVM/Factories/ViewModelFactory.cs
> +        /// <param name="initialize">Specifies if <see cref="IViewModel.InitializeAsync"/> should get called after instance creation.</param>
Codacy found an issue: [Split this 141 characters long line (which is greater than 130 authorized).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060)

2020-06-29 08:35 UTC, Pantheas commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
           

Complexity increasing per file
==============================
- src/MVVM/Factories/ViewModelFactory.cs  1
         

Clones added
============
- src/MVVM/Factories/ViewModelFactory.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5767060&bid=18874753)

2020-06-29 11:22 UTC, merged