Merge feature/wpf navigation into develop
UltimateCodeMonkeys/CodeMonkeys pull request #98
Opened 2020-05-24 11:24 UTC by Pantheas

Added unit tests and fixed issues found while testing

2020-05-25 07:14 UTC, Pantheas commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 25
- Added 39
           

Complexity increasing per file
==============================
- src/tests/UnitTests/Navigation/ViewModels/ParameterViewModel.cs  1
- src/tests/UnitTests/Navigation/ViewModels/SecondViewModel.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
- src/Navigation/WPF/Navigation.WPF/Models/RegistrationInfo.cs  3
- src/tests/UnitTests/Navigation/ViewModels/MainViewModel.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs  1
- src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  1
- src/Navigation/Navigation/ConfigurationBase.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs  1
         

Complexity decreasing per file
==============================
+ src/Navigation/WPF/Navigation.WPF/Models/Configuration.cs  -1
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.show.cs  -2
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs  -2
         

Clones added
============
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
         

Clones removed
==============
+ src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs  -1
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  -1
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746&bid=18279985)

2020-05-25 07:14 UTC, Pantheas commented on src/Core/Navigation/INavigationService.cs
> +        Task ShowAsync<TViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs
> +            if (Configuration.CacheContent)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Use the '?:' operator here.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs
> +            registration.Condition = condition;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to add validation of parameter 'registration' before using it.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Core/Navigation/INavigationService.cs
> +        Task SetRootAsync<TViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Models/Configuration.cs
> +    public class Configuration :
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Change the name of type 'Configuration' to be different from an existing framework namespace.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Models/Configuration.cs
> +    public class Configuration :
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Change the name of type 'Configuration' to be different from an existing framework namespace.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Navigation/Navigation/ConfigurationBase.cs
> +        public bool AllowDifferentViewTypeRegistrationForSameViewModel { get; set; } = false;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove this initialization to 'AllowDifferentViewTypeRegistrationForSameViewModel', the compiler will do that for you.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +                registration.Condition?.Invoke() != false);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unnecessary Boolean literal(s).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Navigation/Navigation/ConfigurationBase.cs
> +        public bool CacheContent { get; set; } = false;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove this initialization to 'CacheContent', the compiler will do that for you.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +        public void ResetRegistrations()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'ResetRegistrations' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs
> +        private void RegisterViewModels()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'RegisterViewModels'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +        public void Unregister<TViewModel, TView>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'Unregister' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Core/Navigation/INavigationService.cs
> +        Task CloseAsync<TViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs
> +                registration.Condition?.Invoke() != false);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unnecessary Boolean literal(s).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs
> +        public static INavigationService Unregister<TViewModel>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:14 UTC, Pantheas commented on src/Navigation/Navigation/ConfigurationBase.cs
> +        public IList<Type> ContentTypesToExcludeFromCaching { get; set; } = new List<Type>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make the 'ContentTypesToExcludeFromCaching' property read-only by removing the property setter or making it private.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:15 UTC, Pantheas commented on src/Core/Navigation/INavigationService.cs
> +        Task CloseAsync<TViewModel, TParentViewModel, TResult>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:15 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs
> +            int expectedRegistrationsCount = 0;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Add the 'const' modifier to 'expectedRegistrationsCount'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:15 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:15 UTC, Pantheas commented on src/Core/Navigation/INavigationService.cs
> +        Task CloseAsync<TViewModel, TParentViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:15 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:15 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +        private static void ThrowIfNotRegistered<TViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'ThrowIfNotRegistered'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:15 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs
> +            int expectedRegistrationsCount = 2;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Add the 'const' modifier to 'expectedRegistrationsCount'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:15 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs
> +        public void ResetRegistrations()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'ResetRegistrations' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:15 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 28
- Added 37
           

Complexity increasing per file
==============================
- src/Navigation/Navigation/ConfigurationBase.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs  1
- src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  1
- src/tests/UnitTests/Navigation/ViewModels/SecondViewModel.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
- src/Navigation/WPF/Navigation.WPF/Models/RegistrationInfo.cs  3
- src/tests/UnitTests/Navigation/ViewModels/MainViewModel.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
- src/tests/UnitTests/Navigation/ViewModels/ParameterViewModel.cs  1
         

Complexity decreasing per file
==============================
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs  -2
+ src/Navigation/WPF/Navigation.WPF/Models/Configuration.cs  -1
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.show.cs  -2
         

Clones added
============
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
         

Clones removed
==============
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  -1
+ src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs  -1
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746&bid=18279985)

2020-05-25 07:16 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs
> +            int expectedRegistrationsCount = 1;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Add the 'const' modifier to 'expectedRegistrationsCount'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +        private static void ThrowIfNotRegistered<TViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs
> +                registration.Condition?.Invoke() != false);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unnecessary Boolean literal(s).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.show.cs
> +            if (registration.ResolveViewUsingDependencyInjection)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Use the '?:' operator here.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Core/Navigation/INavigationService.cs
> +        Task CloseAsync<TViewModel, TParentViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +        private static void ThrowIfNotRegistered<TViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'ThrowIfNotRegistered'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs
> +            if (Configuration.CacheContent)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Use the '?:' operator here.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs
> +        public static INavigationService Unregister<TViewModel>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Core/Navigation/INavigationService.cs
> +        Task ShowAsync<TViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs
> +            throw new NotImplementedException(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Implement this method or throw 'NotSupportedException' instead.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +        public void Unregister<TViewModel, TView>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'Unregister' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.cache.cs
> +        private static TContent AddOrUpdateContentCache<TContent>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'AddOrUpdateContentCache'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs
> +        private TPage AddOrUpdateContentCache<TPage>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Core/Navigation/INavigationService.cs
> +        Task CloseAsync<TViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:16 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.show.cs
> +        private static TView GetContentInstance<TView>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:17 UTC, Pantheas commented on src/Core/Navigation/INavigationService.cs
> +        Task SetRootAsync<TViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:17 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs
> +        public void ResetRegistrations()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'ResetRegistrations' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:17 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.cache.cs
> +        private static TContent AddOrUpdateContentCache<TContent>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:17 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs
> +            int expectedRegistrationsCount = 3;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Add the 'const' modifier to 'expectedRegistrationsCount'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:17 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs
> +        private void RegisterViewModels()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'RegisterViewModels'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:17 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs
> +        public static INavigationService Unregister<TViewModel, TView>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 07:17 UTC, Pantheas commented on src/Core/Navigation/INavigationService.cs
> +        Task ShowAsync<Interface, TData>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to have parameters matching all the type parameters.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 09:37 UTC, LegendaryB requested changes

2020-05-25 09:37 UTC, LegendaryB commented on src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs
> +            registration.Condition = condition;
Null check?

2020-05-25 17:21 UTC, Pantheas commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 22
- Added 18
           

Complexity increasing per file
==============================
- src/tests/UnitTests/Navigation/ViewModels/MainViewModel.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs  1
- src/Navigation/WPF/Navigation.WPF/Models/RegistrationInfo.cs  3
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
- src/tests/UnitTests/Navigation/ViewModels/SecondViewModel.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
- src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  1
- src/tests/UnitTests/Navigation/ViewModels/ParameterViewModel.cs  1
- src/Navigation/Navigation/ConfigurationBase.cs  1
         

Complexity decreasing per file
==============================
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs  -2
+ src/Navigation/WPF/Navigation.WPF/Models/Configuration.cs  -1
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.show.cs  -2
         

Clones added
============
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
         

Clones removed
==============
+ src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs  -1
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs  -1
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746&bid=18279985)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.show.cs
> +            if (registration.ResolveViewUsingDependencyInjection)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Use the '?:' operator here.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs
> +        private void RegisterViewModels()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'RegisterViewModels'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +        public void ResetRegistrations()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'ResetRegistrations' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.cache.cs
> +        private static TContent AddOrUpdateContentCache<TContent>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'AddOrUpdateContentCache'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/Navigation/ConfigurationBase.cs
> +        public IList<Type> ContentTypesToExcludeFromCaching { get; set; } = new List<Type>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make the 'ContentTypesToExcludeFromCaching' property read-only by removing the property setter or making it private.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +        private static void ThrowIfNotRegistered<TViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'ThrowIfNotRegistered'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs
> +        public void ResetRegistrations()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'ResetRegistrations' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Models/Configuration.cs
> +    public class Configuration :
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Change the name of type 'Configuration' to be different from an existing framework namespace.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs
> +            registration.Condition = condition;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to add validation of parameter 'registration' before using it.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.cache.cs
> +        private static TPage AddOrUpdateContentCache<TPage>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'AddOrUpdateContentCache'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs
> +                registration.Condition?.Invoke() != false);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unnecessary Boolean literal(s).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +        public void Unregister<TViewModel, TView>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'Unregister' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +                registration.Condition?.Invoke() != false);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unnecessary Boolean literal(s).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-25 17:21 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Models/Configuration.cs
> +    public class Configuration :
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Change the name of type 'Configuration' to be different from an existing framework namespace.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:29 UTC, Pantheas commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 17
- Added 21
           

Complexity increasing per file
==============================
- src/Navigation/Navigation.Xamarin.Forms/Models/NavigationServiceOptions.cs  1
- src/Navigation/WPF/Navigation.WPF/Service/NavigationService.cache.cs  1
- src/tests/UnitTests/Navigation/ViewModels/MainViewModel.cs  1
- src/Navigation/Navigation/NavigationServiceOptionsBase.cs  1
- src/Navigation/WPF/Navigation.WPF/Models/RegistrationInfo.cs  3
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs  1
- src/tests/UnitTests/Navigation/ViewModels/SecondViewModel.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
- src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  1
- src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.cache.cs  1
- src/tests/UnitTests/Navigation/ViewModels/ParameterViewModel.cs  1
         

Complexity decreasing per file
==============================
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.show.cs  -2
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs  -2
         

Clones added
============
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
         

Clones removed
==============
+ src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs  -1
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs  -1
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746&bid=18279985)

2020-05-27 07:29 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs
> +            registration.Condition = condition;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Refactor this method to add validation of parameter 'registration' before using it.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs
> +        internal async Task<TViewModel> InitializeViewModelInternal<TViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'InitializeViewModelInternal' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +        public void ResetRegistrations()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'ResetRegistrations' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs
> +        private void RegisterViewModels()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'RegisterViewModels'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Models/RegistrationInfo.cs
> +                if (value == null)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Use the '??=' operator here.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +                registration.Condition?.Invoke() != false);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unnecessary Boolean literal(s).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs
> +        public void ResetRegistrations()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'ResetRegistrations' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +        public void Unregister<TViewModel, TView>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'Unregister' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs
> +        internal async Task<TViewModel> InitializeViewModelInternal<TViewModel, TModel>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make 'InitializeViewModelInternal' a static method.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.cache.cs
> +        private static TPage AddOrUpdateContentCache<TPage>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'AddOrUpdateContentCache'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs
> +        private static void ThrowIfNotRegistered<TViewModel>()
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'ThrowIfNotRegistered'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.show.cs
> +            if (registration.ResolveViewUsingDependencyInjection)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Use the '?:' operator here.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.cache.cs
> +                .Contains(registration.ViewType) == true)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unnecessary Boolean literal(s).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/WPF/Navigation.WPF/Service/NavigationService.cache.cs
> +        private static TContent AddOrUpdateContentCache<TContent>(
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unused private method 'AddOrUpdateContentCache'.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs
> +    public partial class NavigationServiceTests
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: ['partial' is gratuitous in this context.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.cache.cs
> +                .Contains(pageType) == true)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unnecessary Boolean literal(s).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs
> +                registration.Condition?.Invoke() != false);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Remove the unnecessary Boolean literal(s).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 07:30 UTC, Pantheas commented on src/Navigation/Navigation/NavigationServiceOptionsBase.cs
> +        public IList<Type> ContentTypesToExcludeFromCaching { get; set; } = new List<Type>();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Make the 'ContentTypesToExcludeFromCaching' property read-only by removing the property setter or making it private.](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 08:11 UTC, Pantheas commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 18
           

Complexity increasing per file
==============================
- src/tests/UnitTests/Navigation/ViewModels/SecondViewModel.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
- src/Navigation/Navigation.Xamarin.Forms/Models/NavigationServiceOptions.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
- src/tests/UnitTests/Navigation/ViewModels/MainViewModel.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs  1
- src/tests/UnitTests/Navigation/ViewModels/ParameterViewModel.cs  1
- src/Navigation/WPF/Navigation.WPF/Service/NavigationService.cache.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs  1
- src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.cache.cs  1
- src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  1
- src/Navigation/WPF/Navigation.WPF/Models/RegistrationInfo.cs  3
- src/Navigation/Navigation/NavigationServiceOptionsBase.cs  1
         

Complexity decreasing per file
==============================
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.show.cs  -2
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs  -2
         

Clones added
============
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
- src/Navigation/Navigation.Xamarin.Forms/Models/Registration/NavigationRegistration.cs  1
- src/Navigation/WPF/Navigation.WPF/Models/RegistrationInfo.cs  1
         

Clones removed
==============
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs  -1
+ src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs  -1
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746&bid=18279985)

2020-05-27 08:25 UTC, Pantheas commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 20
- Added 2
           

Complexity increasing per file
==============================
- src/Navigation/WPF/Navigation.WPF/Models/RegistrationInfo.cs  3
- src/Navigation/WPF/Navigation.WPF/Service/NavigationService.cache.cs  1
- src/tests/UnitTests/Navigation/ViewModels/MainViewModel.cs  1
- src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.cache.cs  1
- src/tests/UnitTests/Navigation/ViewModels/ParameterViewModel.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
- src/tests/UnitTests/Navigation/ViewModels/SecondViewModel.cs  1
- src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
- src/Navigation/Navigation/NavigationServiceOptionsBase.cs  1
- src/Navigation/Navigation.Xamarin.Forms/Models/NavigationServiceOptions.cs  1
         

Complexity decreasing per file
==============================
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.show.cs  -2
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs  -2
         

Clones added
============
- src/Navigation/WPF/Navigation.WPF/Models/RegistrationInfo.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
- src/Navigation/Navigation.Xamarin.Forms/Models/Registration/NavigationRegistration.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
         

Clones removed
==============
+ src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs  -1
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  -1
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746&bid=18279985)

2020-05-27 08:25 UTC, Pantheas commented on src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs
> +                    $"Non-assignable view type specifications for ViewModel '{typeof(TViewModel).Name}' - registered: '{registration.ViewType.Name}', generic parameter: {typeof(TPage).Name}");
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Split this 192 characters long line (which is greater than 120 authorized).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 08:25 UTC, Pantheas commented on src/Navigation/Navigation/NavigationServiceOptionsBase.cs
> +        /// This is required if pages should be prebuilt (<see cref="CodeMonkeys.Navigation.INavigationService.Register{TViewModel}(Type, bool)" />
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Split this 147 characters long line (which is greater than 120 authorized).](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746)

2020-05-27 08:41 UTC, Pantheas commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 20
           

Complexity increasing per file
==============================
- src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  1
- src/tests/UnitTests/Navigation/ViewModels/MainViewModel.cs  1
- src/Navigation/WPF/Navigation.WPF/Service/NavigationService.cache.cs  1
- src/tests/UnitTests/Navigation/ViewModels/SecondViewModel.cs  1
- src/Navigation/WPF/Navigation.WPF/Models/RegistrationInfo.cs  3
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
- src/Navigation/Navigation.Xamarin.Forms/Models/NavigationServiceOptions.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.registration.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.cs  1
- src/Navigation/Navigation/NavigationServiceOptionsBase.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
- src/tests/UnitTests/Navigation/ViewModels/ParameterViewModel.cs  1
- src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.cache.cs  1
         

Complexity decreasing per file
==============================
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.show.cs  -2
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.show.cs  -2
         

Clones added
============
- src/Navigation/Navigation.Xamarin.Forms/Models/Registration/NavigationRegistration.cs  1
- src/Navigation/WPF/Navigation.WPF/Models/RegistrationInfo.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.show.cs  1
- src/tests/UnitTests/Navigation/WPF/NavigationServiceTests.close.cs  1
         

Clones removed
==============
+ src/Navigation/WPF/Navigation.WPF/NavigationServiceExtensions.cs  -1
+ src/Navigation/WPF/Navigation.WPF/Service/NavigationService.registration.cs  -1
+ src/Navigation/Navigation.Xamarin.Forms/Service/NavigationService.registration.cs  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/UltimateCodeMonkeys/CodeMonkeysMVVM/pullRequest?prid=5575746&bid=18279985)

2020-05-27 13:13 UTC, LegendaryB approved these changes

2020-05-27 13:20 UTC, merged